[symlinks]
"~/dott-test/zsh/.zshrc" = "config/zsh/.zshrc"
"~/dott-test/nvim" = "config/nvim"

[scripts.deps]
linux = "scripts/test-linux.sh"
macos = "scripts/test-maxos.sh"

[scripts.custom]
setup = "scripts/test-custom.sh"
